services:
  app:
    image: node:20.5.0-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - mysql_shared-services

networks:
  mysql_shared-services:
    external: false
